---
- hosts: all
  gather_facts: no
  become: true

  tasks:

  - name: Update all packages
    apt:
      upgrade: yes
      update_cache: yes
    register: task_result

  - name: 'Reboot if necessary'
    shell: sleep 10 && /sbin/shutdown -r now 'Rebooting box to update system libs/kernel as needed'
    args:
       removes: /var/run/reboot-required
    async: 1
    poll: 0
    when: task_result is changed
    register: result
    #changed_when: result.stat.exists
    #notify: 'restart server'

  - name: 'Wait for host to become available again'
    wait_for_connection:
     delay: 30
     connect_timeout: 10
     sleep: 10
     timeout: 300
